### ISSUE TITLE
支持Function Call（工具调用）

### ISSUE THREAD

**Issue by geffzhang** [sdcb/Sdcb.DashScope#1]
工具调用（‌Function Calling）‌便指的是，在必要时，模型会调用相应的外部函数或API，帮助模型获得更准确、‌更实时的信息，‌提高模型表现和实用性。‌https://help.aliyun.com/zh/model-studio/user-guide/text-generation?spm=a2c4g.11186623.help-menu-2400256.d_1_0_0.7a51453a49DfrW&scm=20140722.H_2841718._.OR_help-V_1#b5e1375f75n6f

**Comment by sdcb** [comment]
此前dashscope没提供这个功能，我来看看

**Comment by sdcb** [comment]
resolved in 2.0.0
